### ISSUE TITLE
PS3 Memorycard Adapter returns 0x02 instead of 0x01

### ISSUE THREAD

**Issue by mattysweeps** [ShendoXT/memcardrex#21]
https://github.com/ShendoXT/memcardrex/blob/master/MemcardRex/Hardware/PS3MemCardAdaptor.cs#L85

I have a PS3 Memory Card adapter and a PSX memory card. I know the memory card is a PS1 because I can save games on my PSX and see the save blocks in the bios.

When I build and run memcardrex from master, my memory fails to read. I did some debugging and it seems the second byte is 0x02 instead of 0x01. (It's 0x00 when no card is inserted into the adapter)

Per readme instructions my PS3 adapter is using the generic WinUSB driver.

Also if I comment out this check and try to read from the memory card anyways, it doesnt work. This could be a separate issue.

Do you know why I get 0x02? Is there any documentation on the PS3 Memory Card Adapter's protocol?

**Comment by ndepoel** [comment]
Is it an official Memory Card Adaptor from Sony (CECHZM1)? A friend of mine tried to use a third-party memory card adapter that he got off Amazon (a Speedlink-branded one) and it had the same problem. It seems that particular adapter is only capable of reading PS2 memory cards, which is what the 0x02 byte signifies. Even if you put in a PS1 memory card, it will return a 0x02 byte. We went back and forth with a couple of debugging builds of MemCardRex but we couldn't get the adapter to report anything other than PS2 memory cards.

**Comment by mattysweeps** [comment]
![PXL_20210704_201540761.jpg](https://user-images.githubusercontent.com/3052324/124398325-00cef600-dcca-11eb-9cb0-1e76a323b42a.jpg)

It should be the official one. Does the memory card reader have firmware? Maybe it updated to treat all cards as PS2.

Is it possible to read from a PS2 card? What's the difference in protocol between the two? Is the PS2 protocol documented or implemented somewhere?

**Comment by ndepoel** [comment]
That does certainly look like an official Sony adapter. Can you also have a look at the label on the back? It should look like this:
![image](https://user-images.githubusercontent.com/1871603/124607591-49271900-de6e-11eb-92b2-9c4884763e1e.png)

As far as I know there are no firmware updates for the adapter, but I could be wrong. 

A PS2 memory card works very differently from a PS1 card; unlike PS1 cards they don't work with fixed blocks but have a full-fledged file system instead. There's also the MagicGate encryption system which complicates things. It's not impossible to implement, but I think that's far outside the scope of what MemCardRex is designed to do.

Since you mentioned that you already disabled the check in software, simply ignoring the identifier in MemCardRex and reading the card as a PS1 card doesn't sound like it's a solution. For some reason your adapter is incorrectly reporting the card as a PS2 memory card, so it has to be a hardware problem either on the adapter's or on the memory card's side.

Have you tried it with other PS1 memory cards yet? And if possible, can you test the adapter on a PlayStation 3 and see if it's capable of reading the card correctly?

**Comment by ShendoXT** [comment]
Are you able to use the same memory card on PS3 with the official adapter?

**Comment by Invictaz** [comment]
Interesting to read that the Speedlink adapter does not read PS1 cards.

**Comment by tic13** [comment]
I not sure if that is the same case, but i buy five memory card from alliexpress to make the freepsxboot, and memcardrex don't recognize it. with the ps3 sony adapter.They tell "no ps1 memcard detected".
Ps2 and ps1 recognize the memory cards.

But they recognize my old not official memory cards.

**Comment by carmax91** [comment]
Probably you need to add the 7.6 V (some work also with 5V) on the memory card pin 3. 
Some of the clone mc use an internal voltage divider (or other similar method) from pin 3 to get the required voltage and powering the flash and the internal MCU.
