### ISSUE TITLE
Make it easier to consolidate multiple .VMP save files from PSP into single .MCD save file for Duckstation

### ISSUE THREAD

**Issue by ttang4299** [ShendoXT/memcardrex#37]
**I have made an important edit at the bottom of this issue log. Please read it in its entirety before responding appropriately.**

Hi, I have a couple dozen PS1 save files from my PSP that I'm trying to transfer for use with the Duckstation PS1 emulator. Roughly half have the filename of SCEVMC0 and the remaining save files are named SCEVMC1, so I assume they are for memory card slot 1 and memory card slot 2 respectively. See attached screenshot below for the filenames I am working with.

![scevmc](https://user-images.githubusercontent.com/81255709/205793905-ab2f0530-62cd-4ce6-b90f-7c65524639d8.PNG)

~~I'm looking to have all my games share the same 2 memory cards instead of each game using its own memory card, so I want to consolidate all these files into just 2 save files.~~ (**EDIT**: as explained at the bottom, I now much rather prefer the saves remain separate but all batch converted and inserted into their respective folders, so please ignore this statement)

However, every time I open either the files named SCEVMC0 or the files named SCEVMC1 altogether, I get over 40 tabs opened for every single file. It would be cumbersome and time-consuming to drag and drop each file to the one I want saved.

![mcr](https://user-images.githubusercontent.com/81255709/205794505-c15a343b-6bf1-4621-afea-8ffb7eaf0a69.png)

~~I would much rather prefer MemcardRex to automatically detect which memory card the files are for, and then automatically combine all the .VMP save files into 1 or 2 .MCD save files, with just a few simple clicks and without requiring any dragging and dropping~~ (**EDIT**: please ignore this statement). Would that be possible to implement?

**EDIT (Dec 13th 2022)**: I would like to note that the files in the screenshots above were batch extracted by me from individual folders that the PSP made a directory for. For future users of this tool, it might actually be more useful to just batch convert each individual save and output them to their respective folders, as I have learned since that games usually have individual save files for emulation to prevent potential issues. I think it may be possible that Duckstation already searches for saves within these respective folders. Each folder has been named after the game's respective game ID. I will attach more helpful screenshots below to show both what the directory looks like as a whole, and what can be expected to be found inside each folder.

![psx2](https://user-images.githubusercontent.com/81255709/207234946-db2cab52-f429-427d-abec-96f7dd3c56c7.PNG)

![psx3](https://user-images.githubusercontent.com/81255709/207234965-35006e15-7dde-44ff-aa47-856f21ed2c69.PNG)

**Comment by ShendoXT** [comment]
Sorry but this is a bit outside of the scope of MemcardRex but none the less I found a solution for you.
I made a simple batch script which will do the job for you in no time. It works on Windows 10, I tested it.

Simply make a new file called "PSP2Duck.bat", place it in the main directory where all of your other directories are,
paste this code into it and then simply run it.

    @echo off
    setlocal EnableDelayedExpansion 

    if not exist "memcards" mkdir "memcards"

    for /d %%a in ("S*") do (
     set DirName=%%a
     set ProdCode=!DirName:~0,4!-!DirName:~4,5!
     echo Converting "!DirName!" directory to "!ProdCode!" Memory Cards

    if exist !DirName!\SCEVMC0.VMP (
     powershell "gc !DirName!\SCEVMC0.VMP -Encoding byte -Tail 131072 | sc memcards\!ProdCode!_1.mcd -Encoding byte"
     powershell "gc !DirName!\SCEVMC1.VMP -Encoding byte -Tail 131072 | sc memcards\!ProdCode!_2.mcd -Encoding byte"
    )
    )

This will make a new directory called memcards and it will take each card from the respective folder and convert it from .VMP to .mcd which DuckStation use.

The reason this works is simply because VMP files are MCD files with extra 128 byte header. This script removes that header and you are left with the raw .mcd file.

Once you run it, it will take a while, depending on the number of directories you have.
Don't forget to configure DuckStation to use Serial as the base for the Memory Cards.
![converted](https://user-images.githubusercontent.com/8411572/208206554-1d6d30ab-f417-4b8e-b4dd-429ebbe9dc40.png)
![memcards](https://user-images.githubusercontent.com/8411572/208207662-e2ef613e-7967-458f-bc88-8dce65f070b0.png)
